"""Initial migration

Revision ID: 761a3c0d5204
Revises: 
Create Date: 2026-03-07 22:21:54.115247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '761a3c0d5204'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_user',
    sa.Column('id_tiktok_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_thumbnail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_tiktok_user')
    )
    op.create_table('wilayah_kecamatan',
    sa.Column('id_kecamatan', sa.Integer(), nullable=False),
    sa.Column('nama_kecamatan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_kecamatan')
    )
    op.create_table('organisasi_perangkat_daerah',
    sa.Column('id_opd', sa.Integer(), nullable=False),
    sa.Column('nama_opd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('singkatan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deskripsi_tugas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kategori_tugas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiktok_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tiktok_user_id'], ['tiktok_user.id_tiktok_user'], ),
    sa.PrimaryKeyConstraint('id_opd')
    )
    op.create_table('tiktok_video',
    sa.Column('id_tiktok_video', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tiktok_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_web_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tiktok_user_id'], ['tiktok_user.id_tiktok_user'], ),
    sa.PrimaryKeyConstraint('id_tiktok_video')
    )
    op.create_table('wilayah_desa',
    sa.Column('id_desa', sa.BigInteger(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('nama_desa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['wilayah_kecamatan.id_kecamatan'], ),
    sa.PrimaryKeyConstraint('id_desa')
    )
    op.create_table('tiktok_comment',
    sa.Column('id_tiktok_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.Column('create_time_iso', sa.DateTime(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('digg_count', sa.Integer(), nullable=False),
    sa.Column('liked_by_author', sa.Boolean(), nullable=False),
    sa.Column('pinned_by_author', sa.Boolean(), nullable=False),
    sa.Column('replies_to_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reply_comment_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replies_to_id'], ['tiktok_comment.id_tiktok_comment'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tiktok_user.id_tiktok_user'], ),
    sa.ForeignKeyConstraint(['video_id'], ['tiktok_video.id_tiktok_video'], ),
    sa.PrimaryKeyConstraint('id_tiktok_comment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiktok_comment')
    op.drop_table('wilayah_desa')
    op.drop_table('tiktok_video')
    op.drop_table('organisasi_perangkat_daerah')
    op.drop_table('wilayah_kecamatan')
    op.drop_table('tiktok_user')
    # ### end Alembic commands ###
